kind: Service
apiVersion: v1
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # for headless service there is no cluster IP
  selector:
    project: expense
    component: mysql
    tier: db

  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db
  serviceName: "mysql-headless"
  replicas: 2
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      # nodeSelector:
      #   topology.kubernetes.io/zone: us-east-1d  
      containers:
      - name: mysql
        image: prameela0/mysql:v1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword" # Set a strong root password
        - name: MYSQL_DATABASE
          value: "expense_db"
        - name: MYSQL_USER
          value: "expense_user"
        - name: MYSQL_PASSWORD
          value: "password"
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteonce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi
